### ISSUE TITLE
Consider moving integration tests over to `/tests/integration.rs`

### ISSUE THREAD

**Issue by matklad** [DataDog/scipio#117]
Rust has two style of testing -- unit tests inside the lib crate itself, and integration tests in `/tests` dir. Each integration test is a separate crate, which is linked to the library crate and has access only to public API.

I think it makes sense to move tests that can be integration to integration tests.  The benefits are:

* integration test don't have access to private items, so we make sure that we expose all the required API.
* integration test interact with scipio exactly as a client would do (`scipio::foo` over `crate::foo` or `super::foo`), so they can be used to test-drive the ergonomics. 
* integration tests can be a good source of documentation for users of scipio
* by clearly separating unit and integration tests, it would be easier to detect API breaking changes, once we start caring about stability. If you change some code and some tests don't compile, it's fine for unit-tests, and requires a bump of major version in Cargo toml for integrated tests.

**Comment by glommer** [comment]
that's desirable, but we barely have any integration tests at the moment which is why the tests directory is not used.
Is there any test in particular that you think should be moved?

I agree that there is a role to be played with integration tests, but at this point this issue should probably be to write them, not to move them =)

As per the documentation issue, I've been relying mostly on `examples/`

**Comment by matklad** [comment]
Hm, I was under the impression that, eg, all DmaFile tests could be integrated. But I haven't actually checked that, so that might be wrong.

Even if it is wrong though, if I look at random test like

```rust
    dma_file_test!(is_same_file, path, _k, {
        let wfile = DmaFile::create(path.join("testfile")).await.unwrap();
        let rfile = DmaFile::open(path.join("testfile")).await.unwrap();
        let wfile_other = DmaFile::create(path.join("testfile_other")).await.unwrap();

        assert_ne!(wfile.as_raw_fd(), rfile.as_raw_fd());
        assert!(wfile.is_same(&rfile));
        assert!(!wfile.is_same(&wfile_other));

        wfile.close().await.unwrap();
        wfile_other.close().await.unwrap();
        rfile.close().await.unwrap();
    });
```

It seems like it *should* be testing public API?

**Comment by glommer** [comment]
humm.
I think the `DmaFile` tests would indeed use mostly public APIs.
But that's because there's very little if any private functions in those files.

Although they are using the public APIs, they are testing the DmaFile and nothing else. So why shouldn't be local to the crate?

I view integration tests are more essential when they are testing things that may combine many classes.

In terms of keeping sure that the public APIs keep working, won't the documentation tests play a role here?

**Comment by matklad** [comment]
>I view integration tests are more essential when they are testing things that may combine many classes.

I think we might be using the same words to mean different things here.

A (colloquial meaning): "unit test" is a test that checks a single component, and "integrated" test is a test that checks interaction between several component. 

B (cargo's technical meaning): "unit test" is a test in a `#[cfg(test)]` module inside the library crate (same compilation unit), and "integrated" test is a test in a `tests/` folder (different compilation unit). 

You can mix and mach those and have, for example, A"integrated" B"unit" test.

I don't have opinions about organization of tests along A dimension, in this issue I am talking about B. To my mind, it's valuable to test public API via cargo's integrated tests, even if the test itself is small and A"unit". It just gives you a better outside view of the crate, and you step into the shoes of the crate's client for the moment. 

But, again, I don't have strong opinion here.

**Comment by glommer** [comment]
@HippoBaro wondering if you have an opinion here?
My personal view on this is that this only adds to confusion: If you happen to want to test both private and public APIs for a component you now have the tests spread into two places. It gets a bit harder to say "Run all tests for dma_file" (which we can now do by `cargo test dma_file`. You could always require that tests that test the public API for `dma_file` mention that in their names but that is a convention, meaning humans will forget.

`cargo test dma_file` is not a convention, it is machine generated.

I do see a lot of value for integration tests (colloquial meaning) when we test things that combine many components.

**Comment by HippoBaro** [comment]
I think this project is at an early stage and we should prioritize simplicity and flexibility.

That being said, I like the idea of integration tests being separated and only able to use public APIs. 
As a code reader, there is also value in separating them. Our users can treat integration tests as a source of examples and documentation for specific APIs.

But I feel that the latter arguments benefit more mature projects with stable APIs. This is not us... yet!

**Comment by matklad** [comment]
It feels that there is sufficient desire to maintain a status quo here, so closing!
