### ISSUE TITLE
Zulip invitation

### ISSUE THREAD

**Issue by KaiserKarel** [DataDog/scipio#136]
The README states that the Zulip community is the place to ask questions, but that seems to be invite only. Perhaps update the README, or open up the zulip community?

I do have some questions regarding Scipio, but I do not wish to pollute the issue tracker :)

**Comment by glommer** [comment]
Hi! I am new to Zulip myself, and was under the impression that an invite would not be needed.

I definitely intend that to be fully open. Please join through this link for now and I'll see if I can get the settings right

https://scipio.zulipchat.com/join/yzruoxeedpvwaw2uaa7kfi2t/

**Comment by glommer** [comment]
Also if you don't mind trying again, I flipped a setting that I found that said that invitations were indeed needed.
