### ISSUE TITLE
crates.io?

### ISSUE THREAD

**Issue by L1AN0** [DataDog/scipio#34]
It seems that this library is not on crates.io. Any plan to publish it?

**Comment by glommer** [comment]
Hello @L1AN0 .

Yes, this is a nascent library so it will take us some time. One of the impediments now is that crates.io only allow packages that depend on other crates and we have some direct git dependencies for unmerged code on `iou` and `uring-sys`. 

I have experimental patches that import that code directly temporarily.

Give us a couple of days and it should be on crates.

Thanks!

**Comment by glommer** [comment]
quick update on this: `iou` seems to have most of the bits we need now, but `uring-sys` is still broken (lacking a commit that fixes the poll ring)

We'll get there.

**Comment by glommer** [comment]
I just opened https://github.com/ringbahn/uring-sys/issues/22 and https://github.com/ringbahn/uring-sys/issues/23

**Comment by NOBLES5E** [comment]
@glommer  Is it possible to separate executor and `io_uring` related things into different crates?

There are many scenarios where we only need a one thread per core system and don't need `io_uring`. In these cases, an easy way to create local executors on individual threads is good enough.

**Comment by glommer** [comment]
Are you proposing not doing I/O, or doing I/O through something else other than io_uring ?

**Comment by NOBLES5E** [comment]
@glommer In my case not doing I/O.

**Comment by glommer** [comment]
right, but are you not doing File I/O or any kind of I/O?

io_uring in Scipio is responsible for:
* timers
* file I/O (including stdin)
* network I/O.

I feel like it would be too crippling.

All the code we wrote that is needed for io_uring at this point was merged in the io_uring crates. So I don't see a lot of appeal in making that optional.

**Comment by NOBLES5E** [comment]
@glommer Thanks for your  reply :)

**Comment by glommer** [comment]
My pleasure! Please stick around, we'll have a chat soon (follow the discussion on https://github.com/DataDog/scipio/issues/126).

Despite the roadblock with io_uring, I should be able to publish on crates as early as this week. I will temporarily copy the io_uring code to unblock us.

**Comment by NOBLES5E** [comment]
Thanks. I was thinking about if we are not doing I/O ( or we can use something else for I/O), then the lib can be used on systems with an older kernel (since most environments in my company runs on old kernel and I cannot change that )

**Comment by glommer** [comment]
I understand your point.
I wouldn't use scipio in production for a while still =)
Hopefully by then your company will be in newer kernels.

There are advantages in supporting multiple environments but disadvantages too, as complexity grows.
At the moment I think it pays to keep it simple

**Comment by glommer** [comment]
https://crates.io/crates/scipio
