### ISSUE TITLE
What do you think of moving away `create_task_queue` out of Task<T>/Local?

### ISSUE THREAD

**Issue by sitano** [DataDog/scipio#42]
Some functions like `create_task_queue` in the `Task<T>` do not have any dependency on `self` but they can't be accessed via just `Task::func`. Now the workaround is to do `Task::<()>::` or `Local::`. Do you want to keep them in this namespace of we could move them out to the global scope?

**Comment by glommer** [comment]
Hi @sitano 

I prefer to keep them in this namespace, because they need an local executor to run (see how they panic if there isn't one).
I find it helpful that all functions under `Local` communicate that.
